#server:
#  port: 9090
#  
#  spring:
#    datasource:
#    url: jdbc:mysql://localhost:3397/bank_new_apis?useSSL=false
#    username: root
#    password: Admin@2022
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    
#  jpa:
#      hibernate:
#          ddl-auto: update
#      show-sql: true 
#      properties:
#        hiberante:
#          dialect: org.hibernate.dialect.MySQL8Dialect   
